[package]
name = "pokelookup"
description = "Look up pokemon details"
version = "0.1.4"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
futures = "0.3.31"
rustemon = "4.2.0"
tokio = {version="1.46.1", features=["full"]}
