[package]
name = "pokelookup"
description = "Look up pokemon details through PokeAPI."
version = "0.6.4"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive", "wrap_help"] }
futures = "0.3.31"
rustemon = "4.2.0"
serde_json = "1.0.140"
tokio = {version="1.46.1", features=["full"]}
ureq = "3.0.12"
